apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: halidak/apigateway:latest
          ports:
            - containerPort: 8080
          env:
            - name: Urls__Users
              value: "http://science-festival-rest-service:80"
            - name: Urls__Shows
              value: "http://science-festival-go-service:8000"
            - name: Urls__Reviews
              value: "http://science-festival-async-service:80"
      initContainers:
        - name: check-science-festival-rest-service
          image: busybox:1.36.1
          command: ['sh', '-c', 'until wget -qO- http://science-festival-rest-service:80/healthz; do echo waiting for science-festival-rest-service; sleep 2; done;']
        - name: check-science-festival-go-service
          image: busybox:1.36.1
          command: ['sh', '-c', 'until wget -qO- http://science-festival-go-service:8000/healthz; do echo waiting for science-festival-go-service; sleep 2; done;']
        - name: check-science-festival-async-service
          image: busybox:1.36.1
          command: ['sh', '-c', 'until wget -qO- http://science-festival-async-service:80/healthz; do echo waiting for science-festival-async-service; sleep 2; done;']
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  type: NodePort
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80