apiVersion: v1
kind: Service
metadata:
  name: science-festival-rest-service
spec:
  type: NodePort
  selector:
    app: sciencefestivalrest
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80