kind: PersistentVolume
apiVersion: v1
metadata:
  name: sql-server-pv-volume 
  labels:
    type: local 
    app: sql-server
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
    
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sql-server-pv-claim
  labels:
    app: sql-server
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany  
  resources:
    requests:
      storage: 5Gi